# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mastobone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mastobone
  pod 'React', :path => '../node_modules/react-native'
  pod 'React/Core', :path => '../node_modules/react-native'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'mastoboneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

